services:
  postgres:
    image: postgres:16-alpine
    container_name: learnlite-postgres
    environment:
      POSTGRES_DB: learnlite
      POSTGRES_USER: learnlite
      POSTGRES_PASSWORD: learnlite_dev_password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U learnlite -d learnlite"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
